### ISSUE TITLE
No .exe

### ISSUE THREAD

**Issue by amel00** [Microsoft/AADConnectConfigDocumenter#1]
the AzureADConnectSyncDocumenter.cmd is calling an .exe file, AzureADConnectSyncDocumenterCmd.exe

Where is this file located or how do I get in, I read through the readme, hoping it was in there but it is now. 

Thanks

**Comment by NileshGhodekar** [comment]
The zip file AzureADConnectSyncDocumenter.zip on the releases tab has all the files including the .exe.

**Comment by amel00** [comment]
Sorry, thanks I was pulling it from the code section.. I apologize :)

**Comment by NileshGhodekar** [comment]
Cool. Will close this issue now.
