### ISSUE TITLE
Very slow to process / unable to generate the report

### ISSUE THREAD

**Issue by KristofVandenBroeck** [Microsoft/AADConnectConfigDocumenter#11]
Hi,

I have a configuration with 16 connectors and around 500 rules, when I run the tool it takes a day to complete, it seems it is running a very long time on the first part of Processing Metaverse "person" type just before the connectors are processed. See below log snip, it took 19 hours to process changes.

AADConnectSyncDocumenterLog Information: 20000 : AADConnectSyncDocumenter (1.17.0802.0): 10/20/2017 14:36:16.3061:  Metaverse Object Type: 'person'. Processing changes. This may take a few minutes...
AADConnectSyncDocumenterLog Information: 20000 : AADConnectSyncDocumenter (1.17.0802.0): 10/21/2017 09:38:44.0727: Processing Metaverse Object Deletion Rules Summary

Is this a expected time to process at this stage ? 

Then after processing for 23:45 the process ended with an error message that it was unable to access the report file, the Report directory was present but not the "contoso" subfolder.

Thanks,

Kristof

**Comment by NileshGhodekar** [comment]
With 16 connects and each and every of the rules changing (due to precedence number change), this is kind of expected. In fact, I've a personal version that skips documenting End-to-End flows and then it runs much quicker. I'm planning to make it available as a cmdline option to skip these sections that take extraordinarily long time.

**Comment by NileshGhodekar** [comment]
Hi Kristof, download the latest release [v1.17.1023.0](https://github.com/Microsoft/AADConnectConfigDocumenter/releases/tag/v1.171023.0) and try regenerating the report with both the app settings SuppressMetaverseObjectTypeConfigSection and SuppressConnectorImportExportEndToEndFlows to true in the app config file. Let me know the new total time :)

**Comment by KristofVandenBroeck** [comment]
Hi,

Thanks for this new version, runtime with both settings disabled is now running for around 35 minutes.

What consequences does this have for the report, can we still use it to compare the configurations or are we missing data now ? 

Thanks,

Kristof

**Comment by NileshGhodekar** [comment]
Those sections are essentially quick summary sections and typically helpful during development of custom rules. The changes to the sync rule and any other configuration still get document correctly, including sync rule changes script.

**Comment by NileshGhodekar** [comment]
Hi @KristofVandenBroeck, I just make a new release [v1.18.0131.0](https://github.com/Microsoft/AADConnectConfigDocumenter/releases) that promises some good performance improvements. Can you please run the report against your original configuration without any suppression settings and see how long it takes now? Thanks!

**Comment by KristofVandenBroeck** [comment]
Hello,

it is running fine now, 15-20 minutes to process the 16 connectors without the suppression.µ

Thanks!

Kristof Van den Broeck

**Comment by NileshGhodekar** [comment]
Cool. Thanks for the confirmation!
