### ISSUE TITLE
Compare distinct AD and Azure tenant environments

### ISSUE THREAD

**Issue by stevegm999** [Microsoft/AADConnectConfigDocumenter#12]
We have separate DEV, QA and Production environments. Each environment is isolated and has two AD forests including 6 sub domains at various levels and an Azure tenant. I would like to use the tool to compare these to each other (i.e compare DEV to QA and then compare QA to Production).  I have tried modifying the tenant, domain, DN and FQDNs in the config files and have had success but it’s rather time consuming and can be error prone doing that every time.  I’m looking for an option that lets me compare distinct AD and tenant environments.  Maybe something like a mapping file where I could list:
- DOMAIN1 = DOMAIN1DEV
- domain1.company.com = domain1dev.company.com
- dc=domain1,dc=company,dc=com =  dc=domain1dev,dc=company,dc=com
- TenantA.onmicrosoft.com = TenantADEV.onmicrosoft.com
- etc.

This request is similar to what you have addressed before but it would help my ability to compare differences in our complex environment where we take changes through our certification process all the time.  What do you think?

**Comment by NileshGhodekar** [comment]
In my opinion, when comparing the different environments, the only the changes to the sync rules are significant and anything else can be ignored. And that you can do just by updating just the connector name in one set of input config files as mentioned in the instructions on the homepage. However, if you are looking for something more to be treated as a match, I see that as an additional pre-processing activity.  This could be done by writing a simple PowerShell script that does find and replace in all the config files as appropriate. So I'll close this issue now as I think an external pre-processing script is a better design for achieving your goals.

**Comment by stevegm999** [comment]
Modifying the output files does work but can be a mess keeping track of which edits were made to which set of files.  I was thinking that adding a feature like this on the front end would be a cleaner solution.
