### ISSUE TITLE
AzureADConnectSyncDocumenterCmd.exe is missing

### ISSUE THREAD

**Issue by Parroman** [Microsoft/AADConnectConfigDocumenter#13]
Hi,
The .cmd file calls up AzureADConnectSyncDocumenterCmd.exe. This is missing from your download, not showing in source files. Line for the cmd:

**AzureADConnectSyncDocumenterCmd.exe** "Contoso\Pilot" "Contoso\Production"
ECHO OFF
ECHO ****************************************************************************************************
ECHO Execution complete. Please check any errors or warnings in the AADConnectSyncDocumenter-Error.log...
@pause

**Comment by NileshGhodekar** [comment]
The source code that you have downloaded does not include compiled binaries. You should download the "Release" as instructed from the tab / link provided on the homepage. Closing now.
