### ISSUE TITLE
wrong (old) ExportDeletionThresholdValue value

### ISSUE THREAD

**Issue by YassineSOUABNI** [Microsoft/AADConnectConfigDocumenter#14]
Hi,

when running 
"Get-MsolDirSyncConfiguration" or "Get-ADSyncExportDeletionThreshold" 
I get 500

while when running the Documenter tool, I get 
"Microsoft.OptionalFeature.ExportDeletionThresholdValue in the report returns     4500"
(an old value we've replaced back with 500) 

Has someone encountered this ?
Thanks.

**Comment by NileshGhodekar** [comment]
The value in the tenant that these cmdlets are returning will be authoritative. I'm guessing you ran the  Enable-ADSyncExportDeletionThreshold cmdlet from a different server to set it back to 500 and that is why the local server config did not get updated?

**Comment by YassineSOUABNI** [comment]
True, that is what happened.
Thanks for the feedback.

**Comment by NileshGhodekar** [comment]
Thanks for confirming. Closing the issue now.
