### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by WTurgeon** [Microsoft/AADConnectConfigDocumenter#15]
The HTML output file suggests that there are three (possibly four) options that can be configured:

1. Only show Changes
2. Download Sync Rule Changes Script
3. Hide Default Sync Rules
4. Hide End-to-end Summary Flows

But I can find nothing in the documentation regarding how to turn any of them on or off.
What am I missing??

**Comment by dakegg** [comment]
Top of the output HTML file

On Sep 12, 2018 12:34 PM, WTurgeon <notifications@github.com> wrote:

The HTML output file suggests that there are three (possibly four) options that can be configured:

  1.  Only show Changes
  2.  Download Sync Rule Changes Script
  3.  Hide Default Sync Rules
  4.  Hide End-to-end Summary Flows

But I can find nothing in the documentation regarding how to turn any of them on or off.
What am I missing??

**Comment by WTurgeon** [comment]
I know the boxes are at the top of the HTML file, but that does NOTHING to change what the documenter is doing. There would have to be switches or other modifiers in the command line itself to have those changes take effect during the operations. Checking the boxes in the HTML file would be cosmetic at best.

 

For example, checking the box for “Only show Changes”, after the fact, would not change the results shown in the HTML file – it would still show everything that it usually does.

 

Regards,

WTurgeon

**Comment by NileshGhodekar** [comment]
This is strange. Agreed that there is no further documentation on how the checkboxes behave and what and when they hide, generally it's quickly visible and so one can infer how they work. Here is a quick explanation:

•	Only Show Changes – When checked, this will hide all individual config elements that have no changes in them. It will also make “Download Sync Rule Changes Script” link visible.
•	Hide Default Sync Rules – When checked, this will hide all the rules with tag name starting with “Microsoft.”.  If they have any changes in it, they’ll STILL be visible.
•	Hide End-to-end Summary Flows – When checked, this will hide the end-to-end flows in the Metaverse and Connector config sections. 

I'm thinking it may be a browser related issue. Have you tried to play with the  "Contoso" sample config? There are no changes to Pilot/Production sets in that sample so all these visibility changes will be drastic and easy to spot. So try and let us know. Also happy to take a look at your own config report as well if you can send the report to me offline at nileshg@microsoft.com.

**Comment by NileshGhodekar** [comment]
Hello, I'm closing this issue now. I've seen that on older versions of documenter, if you tried to use checkboxes before the page is completely loaded, it would not work. However to prevent this, on the recent versions the checkboxes would be disabled until the page is fully loaded. If you do run into this issue make sure that you are running the latest release and let us know more repro details.
