### ISSUE TITLE
Missing command-line arguments for pilot/production folders

### ISSUE THREAD

**Issue by TC-1927** [Microsoft/AADConnectConfigDocumenter#21]
Hi

However I configure the AzureADConnectSyncDocumenter-Contoso.cmd file, I get the same output:

Missing commnad-line arguments. Usage: AzureADConnectSyncDocumenterCmd {Pilot / Target Config Folder} {Production / Reference / Baseline Config Folder}.
Example:
 AzureADConnectSyncDocumenterCmd "Contoso\Pilot" "Contoso\Production"

The contents of the .cmd file are:

AzureADConnectSyncDocumenterCmd.exe "ORG\New-Server" "ORG\Old-Server"

ECHO OFF

Should I rename the .cmd file AzureADConnectSyncDocumenter-[organistation].cmd?

Any suggestions?

**Comment by NileshGhodekar** [comment]
Hi @TC-1927, I'm closing this as no repro. If you have any additional information  on why you got this error in the first place, please comment.
