### ISSUE TITLE
Group filter group

### ISSUE THREAD

**Issue by barkesteijn** [microsoft/AADConnectConfigDocumenter#25]
Hi,

I created a test AADC instance with group filtering on, but I see this not listed in the report as a configured option on the AD connector. I would like to request this as a feature.

parameter name="Connector.GroupFilteringGroupDn"

The only other way for a admin is to use powershell to get the value.

**Comment by NileshGhodekar** [comment]
Hi @barkesteijn, this is not a connector level setting but a AADC instance config. It should appear as Microsoft.OptionalFeature.GroupFiltering setting under Global Settings settings Please check there.

**Comment by barkesteijn** [comment]
That only specifies if it's configured with true or false.
But I find it useful to know which group is actually used also If you compare the configuration between instances you know what is wrong.

**Comment by barkesteijn** [comment]
![Capture](https://user-images.githubusercontent.com/55348222/71718644-2a306c80-2e1c-11ea-9341-6c998419a792.PNG)

**Comment by barkesteijn** [comment]
But I want this added to the report:
![capture2](https://user-images.githubusercontent.com/55348222/71718874-e5590580-2e1c-11ea-9495-f0c0d69e19dd.png)

**Comment by NileshGhodekar** [comment]
ohh, thx. I thought it should have got automatically printed as part of the AD Connector config, but apparently not. Let me reopen the issue :)

**Comment by NileshGhodekar** [comment]
Version 1.20.0413.0 with the fix is now available.
