### ISSUE TITLE
Error when running the report again

### ISSUE THREAD

**Issue by kajencik** [microsoft/AADConnectConfigDocumenter#29]
I'm getting an error when trying to run the report for second time: 
AADConnectSyncDocumenterLog Error: 40000 : AADConnectSyncDocumenter (1.19.0130.0): 04/01/2020 08:20:13.5947: Exception in 'AzureADConnectSyncDocumenter : GetReport'. Details: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\adminuser\AppData\Local\Temp\2\Report.tmp.html_bcf85dc8d92d44639a837d1f5368c18a'.

Strangely, this now happens even when running the first, Contoso, script.

**Comment by NileshGhodekar** [comment]
May be you rant first with elevate prompt and then running as regular user?

**Comment by NileshGhodekar** [comment]
@kajencik, hopefully that was the reason. Closing this issue now.
