### ISSUE TITLE
Linebreaks missing in generated powershell script

### ISSUE THREAD

**Issue by Robingaal** [Microsoft/AADConnectConfigDocumenter#3]
When generating the powershell script to migrate the changes some line breakes are missing which causes powershell errors. It happens for the 3 custom rules we have created. For example the generated powershell migration code contains this piece:

```
Add-ADSyncRule -SynchronizationRule $syncRule[0] | Out-Null#############################################################################################################################################
#### mydomain - Out to AD - InetOrgPerson Exchange Hybrid
#############################################################################################################################################
```

Which gives the following error in the powershell console (because of the missing linebreak behind "Out-Null" in the generated code):
`Processing Sync Rule 'In from AD - User Exchange - Usage Location' for Connector 'mydomain'
Out-Null#############################################################################
#####################################################################################
########################################################' is not recognized as the na
me of a cmdlet, function, script file, or operable program. Check the spelling of the
 name, or if a path was included, verify that the path is correct and try again.`

I know this can be solved by adding the missing linebreaks myself to the generated powershell script but would be nice if that isn't necessary.

**Comment by NileshGhodekar** [comment]
Yes, this is a little broken in IE. But I believe should be fine in Edge / Chrome. Will be fixed at the time of next release.

**Comment by Robingaal** [comment]
Thanks for the fast work around! Script that is generated with chrome works fine! We will use it via Chrome until a new release is available.

**Comment by NileshGhodekar** [comment]
The latest build has fix for this and some additional changes. Please try. I'll close issue this now.
