### ISSUE TITLE
Documenter crashes when using Directory Extensions Attribute Sync

### ISSUE THREAD

**Issue by chris-graves** [Microsoft/AADConnectConfigDocumenter#4]
Hi
I'm having a problem running the Documenter against a configuration that has Directory Extension Attribute sync enabled.

In the protected void FillConnectorSelectedAttributesDataSet(bool pilotConfig) method - (line 951 of ConnectorDocumentor.cs) the following code is executed

var attributeInfo = connector.XPathSelectElement(".//dsml:attribute-type[dsml:name = '" + attributeName + "']", Documenter.NamespaceManager);

This return a NULL which causes an exception when trying to set the row value later in the method, causing the program to terminate without creating a report.

The attribute name causing an error in our configuration is extension_7b47cfcf830741a8a8f2c7c15d21a18d_adminDescription. I can forward a set of configuration files for the environment if required.

Kind regards

Chris

**Comment by NileshGhodekar** [comment]
It will be faster if you could send the files. nileshg at microsoft.com

**Comment by NileshGhodekar** [comment]
It looks like somehow the config file is in inconsistent state. The only valid config is for extension_7b47cfcf830741a8a8f2c7c15d21a18d_extensionAttribute8, ...11 , ...15 while it's invalid for extension_7b47cfcf830741a8a8f2c7c15d21a18d_**adminDescription**, **...description** and **...wWWHomePage**.  These should not be present in the config any more, but they are there. I'll have this misconfig handled in the next build, but for now the report will run if you delete the later three attributes from the Connector_{b891884f-051e-4a83-95af-2544101c9083}.xml file before running the tool.

**Comment by chris-graves** [comment]
Thanks Nilesh


That's interesting. I just ran through the configuration wizard again and found that we only have extensionAttributes 8,11 and 15 enabled as directory extensions.


However, we had adminDescription, description and wWWHomePage selected as directory extensions at some point in the past when trying to work out why the description attribute was not accessible via Graph API.


I guess that adding a Directory extension attribute and then removing it leaves some traces in the configuration files? Or maybe the fact that the attribute names remain in the metaverse is causing them to appear in our configuration file?


Anyway, thanks for adding code to handle the misconfiguration issue.


Chris

________________________________

**Comment by NileshGhodekar** [comment]
fix checked in. Closing the issue now. Formal release will be along with few other changes.
