### ISSUE TITLE
Connectors and default rules from Pilot to Production

### ISSUE THREAD

**Issue by hich77** [Microsoft/AADConnectConfigDocumenter#9]
Hi Nilesh,

it's a really lovely tools that you've created.  But now on, when we try to create automatically by your script new connectors and their default rules, the new connector are correctly created, but without these default rules.  Isn't there any possibilities to create those rules automatically as when we use the wizard to create a new connector ?

Regards.

**Comment by NileshGhodekar** [comment]
The script does not create connectors. Why do you think it creates connector? For default rules, the only supported change is to make then disabled / enabled. That's the only think the script will do. For any other change detected, it will simply log a warning.

**Comment by hich77** [comment]
Hi Nilesh, 

Sorry was  late for me yesterday evening, and i've mixed both of the settings we've used on our production to get it compliant against our pilot server.  The one who's 'creating' connectors is the powershell command : 
Set-ADSyncServerConfiguration

so it's not due to the script that we've created :-) 

I'm closing that comment !   Sorry for the misunderstanding.
